; ==============================================================================
; Efootball Sider by Toriga - Master Configuration (sider.ini)
; ==============================================================================

[SETTINGS]
mods_directory = "..\..\..\content"
live_asset_loader = 1
live_texture_override = 1
live_mesh_override = 1
live_database_override = 1

[sider]
debug = 1
freecam = 0

[camera]
enabled = 1
zoom = 0.82
height = 1.32
angle = -0.12
fov = 50.0
freecam_speed = 2.5

[OVERLAY]
enabled = 1
hotkey_toggle = "Space"
hotkey_freecam = "F1"

[SERVERS]
kitserver_enabled = 1
stadiumserver_enabled = 1
ballserver_enabled = 1

[LIVE_CPK]
; Registra una root per ogni pacchetto attivo:
cpk.root = "..\..\..\content\database"
